server:
  port: 9090
  context-path: /gradesign
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phone_shopping

  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /
      suffix: .jsp
      date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: com.libei.entity
  mapper-locations: classpath:Mapper/*Mapper.xml
